# Raw data cleaning

This notebook cleans and validates the merged raw dataset created in
`01_merge_raw_datasets.ipynb`.

The objectives are limited to:

1. importing the merged raw dataset;
2. preserving an untouched copy;
3. checking column names and data types;
4. identifying source-specific structural missingness;
5. identifying special missing-value codes;
6. checking categorical values and numeric ranges;
7. applying documented technical cleaning;
8. removing the incompatible `Routine` variable;
9. saving a cleaned but substantively untransformed dataset.

No scales, composite variables, categories, or analytical variables are
constructed in this notebook.

## 1. Import packages and the merged raw dataset

In [1]:
from pathlib import Path

import numpy as np
import pandas as pd

pd.set_option("display.max_columns", 150)
pd.set_option("display.max_rows", 150)
pd.set_option("display.float_format", lambda x: f"{x:.3f}")

In [2]:
DATA_FOLDER = Path(
    r"C:\Users\JonatanPl\OneDrive - JDC\Desktop\Yoni\HighTechProtest - Sampling Wave 2\Python\excel"
)

INPUT_PATH = DATA_FOLDER / "merged_raw_dataset.xlsx"
OUTPUT_PATH = DATA_FOLDER / "clean_raw_dataset.xlsx"
LOG_PATH = DATA_FOLDER / "cleaning_log.xlsx"
INVENTORY_PATH = DATA_FOLDER / "variable_inventory_raw.xlsx"

print(f"Input file exists: {INPUT_PATH.exists()}")

Input file exists: True

In [3]:
df_raw = pd.read_excel(INPUT_PATH)

print(f"Rows: {df_raw.shape[0]:,}")
print(f"Columns: {df_raw.shape[1]:,}")

Rows: 860
Columns: 109

## 2. Preserve an untouched copy

All cleaning operations are performed on a copy. The imported dataframe
`df_raw` remains unchanged throughout the notebook.

In [4]:
df = df_raw.copy()

assert df.shape == (860, 109)
assert df["ResponseId"].is_unique
assert df["ResponseId"].notna().all()

## 3. Initialize the cleaning log

In [5]:
cleaning_log = pd.DataFrame(
    columns=[
        "step",
        "variable",
        "issue",
        "action",
        "affected_cases",
        "justification"
    ]
)

cleaning_log

Empty DataFrame
Columns: [step, variable, issue, action, affected_cases, justification]
Index: []

## 4. Inspect and standardize column names

Column names are checked for leading or trailing spaces, internal spaces, and
duplicates. Only technical name standardization is performed.

In [6]:
column_audit = pd.DataFrame({
    "column": df.columns,
    "leading_or_trailing_space": [
        column != column.strip()
        for column in df.columns
    ],
    "contains_space": [
        " " in column
        for column in df.columns
    ],
    "duplicate_name": df.columns.duplicated()
})

column_audit.loc[
    column_audit[
        [
            "leading_or_trailing_space",
            "contains_space",
            "duplicate_name"
        ]
    ].any(axis=1)
]

,column,leading_or_trailing_space,contains_space,duplicate_name
5,Duration (in seconds),False,True,False

In [7]:
df.columns = df.columns.str.strip()

assert not df.columns.duplicated().any()

### Rename the duration variable

The Qualtrics duration variable contains spaces and parentheses. It is renamed
to a simpler machine-readable name. Its values are not changed.

In [8]:
if "Duration (in seconds)" in df.columns:
    df = df.rename(
        columns={
            "Duration (in seconds)": "DurationSeconds"
        }
    )

    cleaning_log = pd.concat(
        [
            cleaning_log,
            pd.DataFrame([{
                "step": "Standardize column name",
                "variable": "Duration (in seconds)",
                "issue": "Column name contains spaces and parentheses",
                "action": "Renamed to DurationSeconds",
                "affected_cases": len(df),
                "justification": "Improves consistency and usability in Python"
            }])
        ],
        ignore_index=True
    )

assert "DurationSeconds" in df.columns
assert "Duration (in seconds)" not in df.columns

## 5. Create a variable inventory

In [9]:
variable_inventory = pd.DataFrame({
    "variable": df.columns,
    "dtype": df.dtypes.astype(str).values,
    "nonmissing_n": df.notna().sum().values,
    "missing_n": df.isna().sum().values,
    "missing_pct": df.isna().mean().mul(100).values,
    "unique_n": [
        df[column].nunique(dropna=True)
        for column in df.columns
    ]
})

variable_inventory = variable_inventory.sort_values(
    ["missing_pct", "variable"],
    ascending=[False, True]
)

variable_inventory

,variable,dtype,nonmissing_n,missing_n,missing_pct,unique_n
101,Ethnicity_5_TEXT,object,7,853,99.186,6
37,EmploymentStatus_7_TEXT,object,18,842,97.907,17
99,Residence_8_TEXT,object,27,833,96.860,24
96,Party_11_TEXT,object,52,808,93.953,36
43,Occupation_4_TEXT,object,90,770,89.535,77
106,FollowUp_Email,object,133,727,84.535,133
107,Notes,object,300,560,65.116,189
105,FollowUp_Interview,float64,404,456,53.023,2
97,BirthYear,float64,758,102,11.860,53
40,Manager,float64,794,66,7.674,2
44,Role_Description,object,805,55,6.395,673
95,Party,float64,822,38,4.419,12
35,Experience,float64,836,24,2.791,46
102,Religion,float64,843,17,1.977,5
104,Salary,float64,853,7,0.814,6
32,AAID27,float64,857,3,0.349,5
41,TechSector,float64,857,3,0.349,7
28,AAID12,float64,858,2,0.233,5
30,AAID18,float64,858,2,0.233,5
31,AAID26,float64,858,2,0.233,5
33,AAID28,float64,858,2,0.233,5
34,AAID29,float64,858,2,0.233,5
26,AAID4,float64,858,2,0.233,5
103,Education,float64,858,2,0.233,8
93,Ideology2,float64,858,2,0.233,9
82,PostProtest7,float64,858,2,0.233,2
29,AAID14,float64,859,1,0.116,5
23,AAID15,float64,859,1,0.116,5
24,AAID17,float64,859,1,0.116,5
25,AAID24,float64,859,1,0.116,5
27,AAID8,float64,859,1,0.116,5
92,Ideology1,float64,859,1,0.116,9
42,Occupation,float64,859,1,0.116,4
66,Polit_Interest,float64,859,1,0.116,4
83,PostProtest8,float64,859,1,0.116,2
84,PostWar1,float64,859,1,0.116,2
87,PostWar4,float64,859,1,0.116,2
89,PostWar6,float64,859,1,0.116,2
70,PreProtest4,float64,859,1,0.116,2
71,PreProtest5,float64,859,1,0.116,2
73,PreProtest7,float64,859,1,0.116,2
74,PreProtest8,float64,859,1,0.116,2
15,TechProtest_Dispute,float64,859,1,0.116,4
19,Tech_Work_Environmen,float64,859,1,0.116,5
48,V6,float64,859,1,0.116,6
22,AAID11,int64,860,0,0.000,5
20,AAID2,int64,860,0,0.000,5
21,AAID7,int64,860,0,0.000,5
75,Attention_check2,object,860,0,0.000,14
13,Consent,int64,860,0,0.000,1
11,DistributionChannel,object,860,0,0.000,1
5,DurationSeconds,int64,860,0,0.000,580
36,EmploymentStatus,int64,860,0,0.000,7
1,EndDate,datetime64[ns],860,0,0.000,859
100,Ethnicity,int64,860,0,0.000,5
6,Finished,int64,860,0,0.000,1
14,Gender,int64,860,0,0.000,2
3,IPAddress,object,860,0,0.000,850
9,LocationLatitude,float64,860,0,0.000,85
10,LocationLongitude,float64,860,0,0.000,85
76,PostProtest1,int64,860,0,0.000,2
77,PostProtest2,int64,860,0,0.000,2
78,PostProtest3,int64,860,0,0.000,2
79,PostProtest4,int64,860,0,0.000,2
80,PostProtest5,int64,860,0,0.000,2
81,PostProtest6,int64,860,0,0.000,2
85,PostWar2,int64,860,0,0.000,2
86,PostWar3,int64,860,0,0.000,2
88,PostWar5,int64,860,0,0.000,2
90,PostWar7,int64,860,0,0.000,2
91,PostWar8,int64,860,0,0.000,2
67,PreProtest1,int64,860,0,0.000,2
68,PreProtest2,int64,860,0,0.000,2
69,PreProtest3,int64,860,0,0.000,2
72,PreProtest6,int64,860,0,0.000,2
4,Progress,int64,860,0,0.000,1
7,RecordedDate,datetime64[ns],860,0,0.000,860
17,Reform_Harm_Tech,int64,860,0,0.000,4
98,Residence,int64,860,0,0.000,8
8,ResponseId,object,860,0,0.000,860
39,Routine,int64,860,0,0.000,6
0,StartDate,datetime64[ns],860,0,0.000,856
2,Status,int64,860,0,0.000,1
16,TechProtest_Legit,int64,860,0,0.000,5
18,TechProtest_Organize,int64,860,0,0.000,4
12,UserLanguage,object,860,0,0.000,1
47,V1,int64,860,0,0.000,6
49,V10,int64,860,0,0.000,6
45,V11,int64,860,0,0.000,5
51,V12,int64,860,0,0.000,6
57,V13,int64,860,0,0.000,6
61,V14,int64,860,0,0.000,6
46,V15,int64,860,0,0.000,6
62,V16,int64,860,0,0.000,6
58,V17,int64,860,0,0.000,6
52,V18,int64,860,0,0.000,5
53,V19,int64,860,0,0.000,6
60,V2,int64,860,0,0.000,6
64,V20,int64,860,0,0.000,6
50,V21,int64,860,0,0.000,6
56,V3,int64,860,0,0.000,6
59,V4,int64,860,0,0.000,6
65,V5,int64,860,0,0.000,6
63,V7,int64,860,0,0.000,6
54,V8,int64,860,0,0.000,6
55,V9,int64,860,0,0.000,6
94,Vote,int64,860,0,0.000,2
38,War_Impact,int64,860,0,0.000,6
108,data_source,object,860,0,0.000,2

In [10]:
variable_inventory.to_excel(
    INVENTORY_PATH,
    index=False
)

## 6. Identify source-specific structural missingness

The following variables were asked only in the Meta questionnaire. Missing
values among Panel respondents are expected by design.

In [11]:
meta_only_variables = [
    "Ethnicity_5_TEXT",
    "FollowUp_Email",
    "FollowUp_Interview"
]

structural_missingness = pd.DataFrame({
    "variable": meta_only_variables,
    "meta_nonmissing": [
        df.loc[df["data_source"] == "meta", variable].notna().sum()
        for variable in meta_only_variables
    ],
    "panel_nonmissing": [
        df.loc[df["data_source"] == "panel", variable].notna().sum()
        for variable in meta_only_variables
    ],
    "panel_missing": [
        df.loc[df["data_source"] == "panel", variable].isna().sum()
        for variable in meta_only_variables
    ]
})

structural_missingness

             variable  meta_nonmissing  panel_nonmissing  panel_missing
0    Ethnicity_5_TEXT                7                 0            454
1      FollowUp_Email              133                 0            454
2  FollowUp_Interview              404                 0            454

## 7. Inspect imported data types

In [12]:
dtype_summary = (
    df.dtypes
    .astype(str)
    .value_counts()
    .rename_axis("dtype")
    .reset_index(name="number_of_variables")
)

dtype_summary

            dtype  number_of_variables
0           int64                   53
1         float64                   39
2          object                   14
3  datetime64[ns]                    3

In [13]:
object_variables = df.select_dtypes(
    include=["object"]
).columns.tolist()

object_variables

['IPAddress',
 'ResponseId',
 'DistributionChannel',
 'UserLanguage',
 'EmploymentStatus_7_TEXT',
 'Occupation_4_TEXT',
 'Role_Description',
 'Attention_check2',
 'Party_11_TEXT',
 'Residence_8_TEXT',
 'Ethnicity_5_TEXT',
 'FollowUp_Email',
 'Notes',
 'data_source']

In [14]:
for variable in object_variables:
    unique_n = df[variable].nunique(dropna=True)

    if unique_n <= 20:
        print(f"\n{variable}")
        print(
            df[variable]
            .value_counts(dropna=False)
            .head(25)
        )

DistributionChannel
DistributionChannel
anonymous    860
Name: count, dtype: int64

UserLanguage
UserLanguage
HE    860
Name: count, dtype: int64

EmploymentStatus_7_TEXT
EmploymentStatus_7_TEXT
NaN                                                       842
עצמאית                                                      2
עצמאית ויזמת                                                1
בחופשת לידה                                                 1
א.כ.ע                                                       1
חופשת לידה                                                  1
גימלאי ויועץ עצמאי                                          1
משרת אם 8 שעות                                              1
סטודנט ועובד במשרה חלקית                                    1
חופשת לידה                                                  1
מעסיק, שותף בחברה                                           1
עבודה במשרה מלאה וסטודנטית                                  1
חופשת לידה (אבל לפני ואחרי עובדת במשרה מלאה)                1
בעלים של סטרטאפ                                             1
מהנדס תודעה                                                 1
יזמית                                                       1
עבדתי במשרה מלאה ונמצא במילואים מקצועיים מתחילת המלחמה      1
פרילנסר                                                     1
Name: count, dtype: int64

Attention_check2
Attention_check2
tech                                                                                                                              656
Tech                                                                                                                              161
tech                                                                                                                               18
TECH                                                                                                                               12
Tech                                                                                                                                2
"tech"                                                                                                                              2
 tech                                                                                                                               2
“tech”                                                                                                                              1
tech לא השתתפתי במחאת ההיטקיסטים. אני ממש בעד הרפורמה המשפטית. חושבת שמערכת המשפט פה בארץ רקובה וצריך לקחת ממנה את הכח בדחיפות      1
tech - ובכל מקרה - המהפיכה המשפטית החלה כשאהרן ברק רימה את חברי הכנסת והעביר את הרשות המחוקקת לבית המשפט                            1
יחס חיובי ביותר                                                                                                                     1
tect                                                                                                                                1
teck                                                                                                                                1
מובן                                                                                                                                1
Name: count, dtype: int64

Ethnicity_5_TEXT
Ethnicity_5_TEXT
NaN                               853
חסרת דת                             2
פסטאפארי                            1
נאמקי                               1
יהודי שאינו מוכר על ידי הרבנות      1
אתאיסט                              1
בת אדם                              1
Name: count, dtype: int64

data_source
data_source
panel    454
meta     406
Name: count, dtype: int64

## 8. Search for special missing-value codes

In [15]:
text_missing_candidates = [
    "",
    " ",
    "NA",
    "N/A",
    "n/a",
    "null",
    "NULL",
    "None",
    "missing",
    "Missing"
]

candidate_counts = []

for variable in df.select_dtypes(include="object").columns:
    for candidate in text_missing_candidates:
        count = df[variable].eq(candidate).sum()

        if count > 0:
            candidate_counts.append({
                "variable": variable,
                "candidate": candidate,
                "count": count
            })

pd.DataFrame(candidate_counts)

Empty DataFrame
Columns: []
Index: []

In [16]:
numeric_missing_candidates = [
    -999,
    -99,
    -9,
    97,
    98,
    99,
    997,
    998,
    999,
    1752
]

numeric_candidate_counts = []

for variable in df.select_dtypes(include="number").columns:
    for candidate in numeric_missing_candidates:
        count = df[variable].eq(candidate).sum()

        if count > 0:
            numeric_candidate_counts.append({
                "variable": variable,
                "candidate": candidate,
                "count": count
            })

pd.DataFrame(numeric_candidate_counts)

          variable  candidate  count
0  DurationSeconds        997      1
1  DurationSeconds        999      1

## 9. Remove accidental surrounding whitespace

Leading and trailing spaces are removed from text variables. Empty strings are
converted to missing values. The number of changed text values is recorded.

In [17]:
text_columns = df.select_dtypes(include="object").columns

whitespace_changes = 0

for variable in text_columns:
    changed = df[variable].apply(
        lambda value: (
            isinstance(value, str)
            and value != value.strip()
        )
    )

    whitespace_changes += int(changed.sum())

    df[variable] = df[variable].apply(
        lambda value: value.strip()
        if isinstance(value, str)
        else value
    )

df[text_columns] = df[text_columns].replace(
    r"^\s*$",
    np.nan,
    regex=True
)

print(f"Text values changed by whitespace removal: {whitespace_changes}")

Text values changed by whitespace removal: 226

In [18]:
cleaning_log = pd.concat(
    [
        cleaning_log,
        pd.DataFrame([{
            "step": "Remove surrounding whitespace",
            "variable": "All text variables",
            "issue": "Leading or trailing whitespace",
            "action": "Applied str.strip() and converted blank strings to missing",
            "affected_cases": whitespace_changes,
            "justification": "Prevents artificial duplicate text categories"
        }])
    ],
    ignore_index=True
)

## 10. Inspect categorical values

In [19]:
low_cardinality_variables = [
    variable
    for variable in df.columns
    if df[variable].nunique(dropna=True) <= 20
]

print(f"Low-cardinality variables: {len(low_cardinality_variables)}")

Low-cardinality variables: 93

In [20]:
for variable in low_cardinality_variables:
    print(f"\n{'=' * 70}")
    print(variable)

    display(
        pd.crosstab(
            df[variable],
            df["data_source"],
            margins=True,
            dropna=False
        )
    )

======================================================================
Status

data_source  meta  panel  All
Status
0             406    454  860
All           406    454  860

======================================================================
Progress

data_source  meta  panel  All
Progress
100           406    454  860
All           406    454  860

======================================================================
Finished

data_source  meta  panel  All
Finished
1             406    454  860
All           406    454  860

======================================================================
DistributionChannel

data_source          meta  panel  All
DistributionChannel
anonymous             406    454  860
All                   406    454  860

======================================================================
UserLanguage

data_source   meta  panel  All
UserLanguage
HE             406    454  860
All            406    454  860

======================================================================
Consent

data_source  meta  panel  All
Consent
1             406    454  860
All           406    454  860

======================================================================
Gender

data_source  meta  panel  All
Gender
0             256    265  521
1             150    189  339
All           406    454  860

======================================================================
TechProtest_Dispute

data_source          meta  panel     All
TechProtest_Dispute
1.000                 243    212 455.000
2.000                  35     85 120.000
3.000                  71     89 160.000
4.000                  56     68 124.000
 NaN                    1      0     NaN
 All                  406    454 860.000

======================================================================
TechProtest_Legit

data_source        meta  panel  All
TechProtest_Legit
1                   100     93  193
2                    56     56  112
3                    34     68  102
4                    42     97  139
5                   174    140  314
All                 406    454  860

======================================================================
Reform_Harm_Tech

data_source       meta  panel  All
Reform_Harm_Tech
1                   91     46  137
2                   93    108  201
3                   22     64   86
4                  200    236  436
All                406    454  860

======================================================================
TechProtest_Organize

data_source           meta  panel  All
TechProtest_Organize
1                      230    228  458
2                       28     69   97
3                       87     84  171
4                       61     73  134
All                    406    454  860

======================================================================
Tech_Work_Environmen

data_source           meta  panel     All
Tech_Work_Environmen
1.000                   48     68 116.000
2.000                   80    105 185.000
3.000                   86    114 200.000
4.000                   75     87 162.000
5.000                  116     80 196.000
 NaN                     1      0     NaN
 All                   406    454 860.000

======================================================================
AAID2

data_source  meta  panel  All
AAID2
1               5      2    7
2              43     32   75
3              69     89  158
4             165    207  372
5             124    124  248
All           406    454  860

======================================================================
AAID7

data_source  meta  panel  All
AAID7
1              14      6   20
2              57     42   99
3              86    132  218
4             150    193  343
5              99     81  180
All           406    454  860

======================================================================
AAID11

data_source  meta  panel  All
AAID11
1               6      3    9
2              35     31   66
3              45     82  127
4             166    205  371
5             154    133  287
All           406    454  860

======================================================================
AAID15

data_source  meta  panel     All
AAID15
1.000           8      2  10.000
2.000          57     55 112.000
3.000         109    155 264.000
4.000         140    176 316.000
5.000          91     66 157.000
 NaN            1      0     NaN
 All          406    454 860.000

======================================================================
AAID17

data_source  meta  panel     All
AAID17
1.000           4      8  12.000
2.000          40     39  79.000
3.000          66    131 197.000
4.000         185    187 372.000
5.000         111     88 199.000
 NaN            0      1     NaN
 All          406    454 860.000

======================================================================
AAID24

data_source  meta  panel     All
AAID24
1.000           3      5   8.000
2.000          35     19  54.000
3.000          71     82 153.000
4.000         147    223 370.000
5.000         149    125 274.000
 NaN            1      0     NaN
 All          406    454 860.000

======================================================================
AAID4

data_source  meta  panel     All
AAID4
1.000           2      1   3.000
2.000          14     23  37.000
3.000          79    102 181.000
4.000         179    214 393.000
5.000         130    114 244.000
 NaN            2      0     NaN
 All          406    454 860.000

======================================================================
AAID8

data_source  meta  panel     All
AAID8
1.000           3      1   4.000
2.000          31     28  59.000
3.000          93    116 209.000
4.000         187    200 387.000
5.000          91    109 200.000
 NaN            1      0     NaN
 All          406    454 860.000

======================================================================
AAID12

data_source  meta  panel     All
AAID12
1.000           1      1   2.000
2.000          11     10  21.000
3.000          40     55  95.000
4.000         161    209 370.000
5.000         191    179 370.000
 NaN            2      0     NaN
 All          406    454 860.000

======================================================================
AAID14

data_source  meta  panel     All
AAID14
1.000          14      8  22.000
2.000          81     77 158.000
3.000         140    168 308.000
4.000         117    138 255.000
5.000          53     63 116.000
 NaN            1      0     NaN
 All          406    454 860.000

======================================================================
AAID18

data_source  meta  panel     All
AAID18
1.000           6      2   8.000
2.000          55     31  86.000
3.000          94    122 216.000
4.000         153    185 338.000
5.000          96    114 210.000
 NaN            2      0     NaN
 All          406    454 860.000

======================================================================
AAID26

data_source  meta  panel     All
AAID26
1.000           1      1   2.000
2.000          11     11  22.000
3.000          81     70 151.000
4.000         184    216 400.000
5.000         127    156 283.000
 NaN            2      0     NaN
 All          406    454 860.000

======================================================================
AAID27

data_source  meta  panel     All
AAID27
1.000           2      1   3.000
2.000          15     17  32.000
3.000          68     86 154.000
4.000         184    212 396.000
5.000         134    138 272.000
 NaN            3      0     NaN
 All          406    454 860.000

======================================================================
AAID28

data_source  meta  panel     All
AAID28
1.000           3      3   6.000
2.000          13     11  24.000
3.000          57     51 108.000
4.000         189    232 421.000
5.000         142    157 299.000
 NaN            2      0     NaN
 All          406    454 860.000

======================================================================
AAID29

data_source  meta  panel     All
AAID29
1.000           2      2   4.000
2.000           8     14  22.000
3.000          64     79 143.000
4.000         205    222 427.000
5.000         125    137 262.000
 NaN            2      0     NaN
 All          406    454 860.000

======================================================================
EmploymentStatus

data_source       meta  panel  All
EmploymentStatus
1                  366    401  767
2                   13     18   31
3                    7     17   24
4                    7      4   11
5                    1      1    2
6                    1      6    7
7                   11      7   18
All                406    454  860

======================================================================
EmploymentStatus_7_TEXT

data_source                                         meta  panel     All
EmploymentStatus_7_TEXT
א.כ.ע                                                  0      1   1.000
בחופשת לידה                                            0      1   1.000
בעלים של סטרטאפ                                        1      0   1.000
גימלאי ויועץ עצמאי                                     0      1   1.000
חופשת לידה                                             1      1   2.000
חופשת לידה (אבל לפני ואחרי עובדת במשרה מלאה)           1      0   1.000
יזמית                                                  1      0   1.000
מהנדס תודעה                                            1      0   1.000
מעסיק, שותף בחברה                                      1      0   1.000
משרת אם 8 שעות                                         0      1   1.000
סטודנט ועובד במשרה חלקית                               0      1   1.000
עבדתי במשרה מלאה ונמצא במילואים מקצועיים מתחילת...     1      0   1.000
עבודה במשרה מלאה וסטודנטית                             1      0   1.000
עצמאית                                                 2      0   2.000
עצמאית ויזמת                                           1      0   1.000
פרילנסר                                                0      1   1.000
NaN                                                  395    447     NaN
All                                                  406    454 860.000

======================================================================
War_Impact

data_source  meta  panel  All
War_Impact
1               5      5   10
2              65     25   90
3               2      3    5
4              38     26   64
5             270    376  646
6              26     19   45
All           406    454  860

======================================================================
Routine

data_source  meta  panel  All
Routine
1              11     18   29
2              62      0   62
3             213      0  213
4             120    109  229
5               0    220  220
6               0    107  107
All           406    454  860

======================================================================
Manager

data_source  meta  panel     All
Manager
1.000         127    121 248.000
2.000         249    297 546.000
 NaN           30     36     NaN
 All          406    454 860.000

======================================================================
TechSector

data_source  meta  panel     All
TechSector
1.000           3      2   5.000
2.000          41     49  90.000
3.000          10     12  22.000
4.000         154    225 379.000
5.000          47     52  99.000
6.000         127     82 209.000
7.000          22     31  53.000
 NaN            2      1     NaN
 All          406    454 860.000

======================================================================
Occupation

data_source  meta  panel     All
Occupation
1.000         304    263 567.000
2.000          48     75 123.000
3.000          13     65  78.000
4.000          40     51  91.000
 NaN            1      0     NaN
 All          406    454 860.000

======================================================================
V11

data_source  meta  panel  All
V11
2              16     10   26
3              59     82  141
4              47     52   99
5             125    158  283
6             159    152  311
All           406    454  860

======================================================================
V15

data_source  meta  panel  All
V15
1              30     57   87
2             159    134  293
3             127    149  276
4              36     44   80
5              36     50   86
6              18     20   38
All           406    454  860

======================================================================
V1

data_source  meta  panel  All
V1
1               1      4    5
2              33     29   62
3              94    132  226
4              50     73  123
5             121    130  251
6             107     86  193
All           406    454  860

======================================================================
V6

data_source  meta  panel     All
V6
1.000          10     19  29.000
2.000          93    107 200.000
3.000         150    143 293.000
4.000          51     63 114.000
5.000          71     83 154.000
6.000          30     39  69.000
 NaN            1      0     NaN
 All          406    454 860.000

======================================================================
V10

data_source  meta  panel  All
V10
1              10      4   14
2              74     43  117
3             150    140  290
4              69     64  133
5              74    135  209
6              29     68   97
All           406    454  860

======================================================================
V21

data_source  meta  panel  All
V21
1              10      4   14
2              77     56  133
3             150    135  285
4              70     86  156
5              75    105  180
6              24     68   92
All           406    454  860

======================================================================
V12

data_source  meta  panel  All
V12
1               5      1    6
2               8     12   20
3              35     40   75
4              99    105  204
5             165    172  337
6              94    124  218
All           406    454  860

======================================================================
V18

data_source  meta  panel  All
V18
2               6      2    8
3              12     12   24
4              55     59  114
5             161    171  332
6             172    210  382
All           406    454  860

======================================================================
V19

data_source  meta  panel  All
V19
1               9     11   20
2              37     40   77
3              89     85  174
4              80    116  196
5             108     99  207
6              83    103  186
All           406    454  860

======================================================================
V8

data_source  meta  panel  All
V8
1               2      2    4
2              13     17   30
3              40     48   88
4              90    132  222
5             143    165  308
6             118     90  208
All           406    454  860

======================================================================
V9

data_source  meta  panel  All
V9
1               5     15   20
2              55     30   85
3              74     58  132
4              92     87  179
5             117    140  257
6              63    124  187
All           406    454  860

======================================================================
V3

data_source  meta  panel  All
V3
1               3      4    7
2              21     17   38
3              34     43   77
4              72    102  174
5             124    152  276
6             152    136  288
All           406    454  860

======================================================================
V13

data_source  meta  panel  All
V13
1               1      1    2
2              19     23   42
3              41     59  100
4              66     88  154
5             168    152  320
6             111    131  242
All           406    454  860

======================================================================
V17

data_source  meta  panel  All
V17
1               6      5   11
2              35     39   74
3              73     81  154
4             129    128  257
5             115    133  248
6              48     68  116
All           406    454  860

======================================================================
V4

data_source  meta  panel  All
V4
1               1      0    1
2              15     18   33
3              34     43   77
4              69    107  176
5             166    162  328
6             121    124  245
All           406    454  860

======================================================================
V2

data_source  meta  panel  All
V2
1              15     17   32
2              89     84  173
3             119    121  240
4              96     96  192
5              68     94  162
6              19     42   61
All           406    454  860

======================================================================
V14

data_source  meta  panel  All
V14
1               0      5    5
2               7      3   10
3              26     31   57
4              24     24   48
5             115    123  238
6             234    268  502
All           406    454  860

======================================================================
V16

data_source  meta  panel  All
V16
1              12      5   17
2              53     29   82
3              88    109  197
4              46     59  105
5             130    134  264
6              77    118  195
All           406    454  860

======================================================================
V7

data_source  meta  panel  All
V7
1              17      8   25
2              61     47  108
3             101    120  221
4              65     70  135
5             117    136  253
6              45     73  118
All           406    454  860

======================================================================
V20

data_source  meta  panel  All
V20
1              81     68  149
2              83     91  174
3              76     91  167
4              31     35   66
5              78     68  146
6              57    101  158
All           406    454  860

======================================================================
V5

data_source  meta  panel  All
V5
1               3      2    5
2              52     30   82
3             106    110  216
4              63     58  121
5             130    149  279
6              52    105  157
All           406    454  860

======================================================================
Polit_Interest

data_source     meta  panel     All
Polit_Interest
1.000              5     43  48.000
2.000             43     97 140.000
3.000            142    188 330.000
4.000            215    126 341.000
 NaN               1      0     NaN
 All             406    454 860.000

======================================================================
PreProtest1

data_source  meta  panel  All
PreProtest1
0             330    425  755
1              76     29  105
All           406    454  860

======================================================================
PreProtest2

data_source  meta  panel  All
PreProtest2
0             352    437  789
1              54     17   71
All           406    454  860

======================================================================
PreProtest3

data_source  meta  panel  All
PreProtest3
0             379    439  818
1              27     15   42
All           406    454  860

======================================================================
PreProtest4

data_source  meta  panel     All
PreProtest4
0.000         324    403 727.000
1.000          82     50 132.000
 NaN            0      1     NaN
 All          406    454 860.000

======================================================================
PreProtest5

data_source  meta  panel     All
PreProtest5
0.000         163    251 414.000
1.000         242    203 445.000
 NaN            1      0     NaN
 All          406    454 860.000

======================================================================
PreProtest6

data_source  meta  panel  All
PreProtest6
0             239    342  581
1             167    112  279
All           406    454  860

======================================================================
PreProtest7

data_source  meta  panel     All
PreProtest7
0.000         263    322 585.000
1.000         142    132 274.000
 NaN            1      0     NaN
 All          406    454 860.000

======================================================================
PreProtest8

data_source  meta  panel     All
PreProtest8
0.000         149    310 459.000
1.000         256    144 400.000
 NaN            1      0     NaN
 All          406    454 860.000

======================================================================
Attention_check2

data_source                                         meta  panel  All
Attention_check2
"tech"                                                 1      1    2
TECH                                                   0     12   12
Tech                                                  73     90  163
tech                                                 331    345  676
tech - ובכל מקרה - המהפיכה המשפטית החלה כשאהרן ...     0      1    1
tech לא השתתפתי במחאת ההיטקיסטים. אני ממש בעד ה...     0      1    1
teck                                                   0      1    1
tect                                                   0      1    1
יחס חיובי ביותר                                        0      1    1
מובן                                                   0      1    1
“tech”                                                 1      0    1
All                                                  406    454  860

======================================================================
PostProtest1

data_source   meta  panel  All
PostProtest1
0              330    433  763
1               76     21   97
All            406    454  860

======================================================================
PostProtest2

data_source   meta  panel  All
PostProtest2
0              354    439  793
1               52     15   67
All            406    454  860

======================================================================
PostProtest3

data_source   meta  panel  All
PostProtest3
0              375    445  820
1               31      9   40
All            406    454  860

======================================================================
PostProtest4

data_source   meta  panel  All
PostProtest4
0              263    385  648
1              143     69  212
All            406    454  860

======================================================================
PostProtest5

data_source   meta  panel  All
PostProtest5
0              179    259  438
1              227    195  422
All            406    454  860

======================================================================
PostProtest6

data_source   meta  panel  All
PostProtest6
0              142    325  467
1              264    129  393
All            406    454  860

======================================================================
PostProtest7

data_source   meta  panel     All
PostProtest7
0.000          289    353 642.000
1.000          115    101 216.000
 NaN             2      0     NaN
 All           406    454 860.000

======================================================================
PostProtest8

data_source   meta  panel     All
PostProtest8
0.000          131    302 433.000
1.000          274    152 426.000
 NaN             1      0     NaN
 All           406    454 860.000

======================================================================
PostWar1

data_source  meta  panel     All
PostWar1
0.000         328    433 761.000
1.000          77     21  98.000
 NaN            1      0     NaN
 All          406    454 860.000

======================================================================
PostWar2

data_source  meta  panel  All
PostWar2
0             374    446  820
1              32      8   40
All           406    454  860

======================================================================
PostWar3

data_source  meta  panel  All
PostWar3
0             381    441  822
1              25     13   38
All           406    454  860

======================================================================
PostWar4

data_source  meta  panel     All
PostWar4
0.000         249    354 603.000
1.000         156    100 256.000
 NaN            1      0     NaN
 All          406    454 860.000

======================================================================
PostWar5

data_source  meta  panel  All
PostWar5
0             203    276  479
1             203    178  381
All           406    454  860

======================================================================
PostWar6

data_source  meta  panel     All
PostWar6
0.000         210    344 554.000
1.000         195    110 305.000
 NaN            1      0     NaN
 All          406    454 860.000

======================================================================
PostWar7

data_source  meta  panel  All
PostWar7
0             281    342  623
1             125    112  237
All           406    454  860

======================================================================
PostWar8

data_source  meta  panel  All
PostWar8
0             127    293  420
1             279    161  440
All           406    454  860

======================================================================
Ideology1

data_source  meta  panel     All
Ideology1
1.000          62     11  73.000
2.000          12     10  22.000
3.000          74     38 112.000
4.000           7     18  25.000
5.000          35    100 135.000
6.000           9     27  36.000
7.000          58     87 145.000
8.000          20     65  85.000
9.000         128     98 226.000
 NaN            1      0     NaN
 All          406    454 860.000

======================================================================
Ideology2

data_source  meta  panel     All
Ideology2
1.000          55     23  78.000
2.000           9      9  18.000
3.000          59     70 129.000
4.000           6     14  20.000
5.000          72    128 200.000
6.000           3     20  23.000
7.000          62     86 148.000
8.000          21     49  70.000
9.000         117     55 172.000
 NaN            2      0     NaN
 All          406    454 860.000

======================================================================
Vote

data_source  meta  panel  All
Vote
1             398    428  826
2               8     26   34
All           406    454  860

======================================================================
Party

data_source  meta  panel     All
Party
1.000          66     67 133.000
2.000          51    131 182.000
3.000          64     44 108.000
4.000          39     62 101.000
5.000           1      9  10.000
6.000           1     31  32.000
7.000          24     30  54.000
8.000           2      0   2.000
9.000           2      1   3.000
10.000         53     22  75.000
11.000         34     20  54.000
12.000         57     11  68.000
 NaN           12     26     NaN
 All          406    454 860.000

======================================================================
Residence

data_source  meta  panel  All
Residence
1             110     50  160
2             172    234  406
3              37     81  118
4              44     32   76
5              10     30   40
6              19      8   27
7               5      1    6
8               9     18   27
All           406    454  860

======================================================================
Ethnicity

data_source  meta  panel  All
Ethnicity
1             396    450  846
2               1      2    3
3               0      2    2
4               1      0    1
5               8      0    8
All           406    454  860

======================================================================
Ethnicity_5_TEXT

data_source                     meta  panel     All
Ethnicity_5_TEXT
אתאיסט                             1      0   1.000
בת אדם                             1      0   1.000
חסרת דת                            2      0   2.000
יהודי שאינו מוכר על ידי הרבנות     1      0   1.000
נאמקי                              1      0   1.000
פסטאפארי                           1      0   1.000
NaN                              399    454     NaN
All                              406    454 860.000

======================================================================
Religion

data_source  meta  panel     All
Religion
1.000           4     46  50.000
2.000          64     43 107.000
3.000          18     16  34.000
4.000          61     57 118.000
5.000         248    286 534.000
 NaN           11      6     NaN
 All          406    454 860.000

======================================================================
Education

data_source  meta  panel     All
Education
1.000           3      8  11.000
2.000          27     22  49.000
3.000           8     85  93.000
4.000         214    226 440.000
5.000         127     82 209.000
6.000          20      7  27.000
7.000           7     21  28.000
8.000           0      1   1.000
 NaN            0      2     NaN
 All          406    454 860.000

======================================================================
Salary

data_source  meta  panel     All
Salary
1.000           0      6   6.000
2.000           0      5   5.000
3.000           7     15  22.000
4.000          23     94 117.000
5.000          58    160 218.000
6.000         315    170 485.000
 NaN            3      4     NaN
 All          406    454 860.000

======================================================================
FollowUp_Interview

data_source         meta  panel     All
FollowUp_Interview
1.000                146      0 146.000
2.000                258      0 258.000
 NaN                   2    454     NaN
 All                 406    454 860.000

======================================================================
data_source

data_source  meta  panel  All
data_source
meta          406      0  406
panel           0    454  454
All           406    454  860

## 11. Inspect numeric ranges

In [21]:
numeric_ranges = pd.DataFrame({
    "variable": df.select_dtypes(include="number").columns,
    "nonmissing_n": [
        df[variable].notna().sum()
        for variable in df.select_dtypes(include="number").columns
    ],
    "min": [
        df[variable].min()
        for variable in df.select_dtypes(include="number").columns
    ],
    "max": [
        df[variable].max()
        for variable in df.select_dtypes(include="number").columns
    ],
    "unique_n": [
        df[variable].nunique(dropna=True)
        for variable in df.select_dtypes(include="number").columns
    ]
})

numeric_ranges

                variable  nonmissing_n      min        max  unique_n
0                 Status           860    0.000      0.000         1
1               Progress           860  100.000    100.000         1
2        DurationSeconds           860  270.000 270542.000       580
3               Finished           860    1.000      1.000         1
4       LocationLatitude           860  -37.816     52.520        85
5      LocationLongitude           860 -118.329    144.967        85
6                Consent           860    1.000      1.000         1
7                 Gender           860    0.000      1.000         2
8    TechProtest_Dispute           859    1.000      4.000         4
9      TechProtest_Legit           860    1.000      5.000         5
10      Reform_Harm_Tech           860    1.000      4.000         4
11  TechProtest_Organize           860    1.000      4.000         4
12  Tech_Work_Environmen           859    1.000      5.000         5
13                 AAID2           860    1.000      5.000         5
14                 AAID7           860    1.000      5.000         5
15                AAID11           860    1.000      5.000         5
16                AAID15           859    1.000      5.000         5
17                AAID17           859    1.000      5.000         5
18                AAID24           859    1.000      5.000         5
19                 AAID4           858    1.000      5.000         5
20                 AAID8           859    1.000      5.000         5
21                AAID12           858    1.000      5.000         5
22                AAID14           859    1.000      5.000         5
23                AAID18           858    1.000      5.000         5
24                AAID26           858    1.000      5.000         5
25                AAID27           857    1.000      5.000         5
26                AAID28           858    1.000      5.000         5
27                AAID29           858    1.000      5.000         5
28            Experience           836    1.000     60.000        46
29      EmploymentStatus           860    1.000      7.000         7
30            War_Impact           860    1.000      6.000         6
31               Routine           860    1.000      6.000         6
32               Manager           794    1.000      2.000         2
33            TechSector           857    1.000      7.000         7
34            Occupation           859    1.000      4.000         4
35                   V11           860    2.000      6.000         5
36                   V15           860    1.000      6.000         6
37                    V1           860    1.000      6.000         6
38                    V6           859    1.000      6.000         6
39                   V10           860    1.000      6.000         6
40                   V21           860    1.000      6.000         6
41                   V12           860    1.000      6.000         6
42                   V18           860    2.000      6.000         5
43                   V19           860    1.000      6.000         6
44                    V8           860    1.000      6.000         6
45                    V9           860    1.000      6.000         6
46                    V3           860    1.000      6.000         6
47                   V13           860    1.000      6.000         6
48                   V17           860    1.000      6.000         6
49                    V4           860    1.000      6.000         6
50                    V2           860    1.000      6.000         6
51                   V14           860    1.000      6.000         6
52                   V16           860    1.000      6.000         6
53                    V7           860    1.000      6.000         6
54                   V20           860    1.000      6.000         6
55                    V5           860    1.000      6.000         6
56        Polit_Interest           859    1.000      4.000         4
57           PreProtest1           860    0.000      1.000         2
58           PreProtest2           860    0.000      1.000         2
59           PreProtest3           860    0.000      1.000         2
60           PreProtest4           859    0.000      1.000         2
61           PreProtest5           859    0.000      1.000         2
62           PreProtest6           860    0.000      1.000         2
63           PreProtest7           859    0.000      1.000         2
64           PreProtest8           859    0.000      1.000         2
65          PostProtest1           860    0.000      1.000         2
66          PostProtest2           860    0.000      1.000         2
67          PostProtest3           860    0.000      1.000         2
68          PostProtest4           860    0.000      1.000         2
69          PostProtest5           860    0.000      1.000         2
70          PostProtest6           860    0.000      1.000         2
71          PostProtest7           858    0.000      1.000         2
72          PostProtest8           859    0.000      1.000         2
73              PostWar1           859    0.000      1.000         2
74              PostWar2           860    0.000      1.000         2
75              PostWar3           860    0.000      1.000         2
76              PostWar4           859    0.000      1.000         2
77              PostWar5           860    0.000      1.000         2
78              PostWar6           859    0.000      1.000         2
79              PostWar7           860    0.000      1.000         2
80              PostWar8           860    0.000      1.000         2
81             Ideology1           859    1.000      9.000         9
82             Ideology2           858    1.000      9.000         9
83                  Vote           860    1.000      2.000         2
84                 Party           822    1.000     12.000        12
85             BirthYear           758 1943.000   2001.000        53
86             Residence           860    1.000      8.000         8
87             Ethnicity           860    1.000      5.000         5
88              Religion           843    1.000      5.000         5
89             Education           858    1.000      8.000         8
90                Salary           853    1.000      6.000         6
91    FollowUp_Interview           404    1.000      2.000         2

## 12. Compare numeric ranges across sources

In [22]:
shared_numeric_variables = list(
    df.select_dtypes(include="number").columns
)

source_range_comparison = []

for variable in shared_numeric_variables:
    source_range_comparison.append({
        "variable": variable,
        "meta_min": df.loc[df["data_source"] == "meta", variable].min(),
        "meta_max": df.loc[df["data_source"] == "meta", variable].max(),
        "panel_min": df.loc[df["data_source"] == "panel", variable].min(),
        "panel_max": df.loc[df["data_source"] == "panel", variable].max()
    })

source_range_comparison = pd.DataFrame(
    source_range_comparison
)

source_range_comparison.loc[
    (source_range_comparison["meta_min"]
     != source_range_comparison["panel_min"])
    |
    (source_range_comparison["meta_max"]
     != source_range_comparison["panel_max"])
]

              variable  meta_min   meta_max  panel_min  panel_max
2      DurationSeconds   319.000 115604.000    270.000 270542.000
4     LocationLatitude   -37.816     52.520     14.505     52.382
5    LocationLongitude  -118.329    144.967   -118.261    136.906
28          Experience     1.000     60.000      1.000     55.000
31             Routine     1.000      4.000      1.000      6.000
49                  V4     1.000      6.000      2.000      6.000
51                 V14     2.000      6.000      1.000      6.000
85           BirthYear  1948.000   2001.000   1943.000   2000.000
87           Ethnicity     1.000      5.000      1.000      3.000
89           Education     1.000      7.000      1.000      8.000
90              Salary     3.000      6.000      1.000      6.000
91  FollowUp_Interview     1.000      2.000        NaN        NaN

## 13. Remove the `Routine` variable

The `Routine` variable uses incompatible numeric coding across the Meta and
Panel datasets. Because the response categories cannot be harmonized reliably
from the available raw files, the variable is removed from the cleaned dataset.

No respondent records are removed.

In [23]:
assert "Routine" in df.columns

df = df.drop(columns=["Routine"])

assert "Routine" not in df.columns

cleaning_log = pd.concat(
    [
        cleaning_log,
        pd.DataFrame([{
            "step": "Remove incompatible variable",
            "variable": "Routine",
            "issue": (
                "The Meta and Panel datasets use incompatible numeric coding "
                "for this variable"
            ),
            "action": "Dropped variable from the cleaned dataset",
            "affected_cases": len(df),
            "justification": (
                "The coding could not be harmonized reliably without confirmed "
                "response-label correspondence"
            )
        }])
    ],
    ignore_index=True
)

print(f"Rows: {df.shape[0]:,}")
print(f"Columns: {df.shape[1]:,}")

Rows: 860
Columns: 108

## 14. Check exact duplicate rows

In [24]:
exact_duplicate_rows = df.duplicated().sum()

print(f"Exact duplicate rows: {exact_duplicate_rows}")

Exact duplicate rows: 0

## 15. Record unusually long survey durations

Long completion times are retained because both source datasets already passed
the predefined quality threshold. They may reflect respondents leaving the
survey window open.

In [25]:
df["DurationSeconds"].describe(
    percentiles=[0.50, 0.75, 0.90, 0.95, 0.99]
)

count      860.000
mean      2123.065
std      13164.618
min        270.000
50%        647.500
75%        891.250
90%       1439.400
95%       2397.800
99%      29163.880
max     270542.000
Name: DurationSeconds, dtype: float64

In [26]:
cleaning_log = pd.concat(
    [
        cleaning_log,
        pd.DataFrame([{
            "step": "Inspect survey duration",
            "variable": "DurationSeconds",
            "issue": "Several unusually long completion times",
            "action": "No change made",
            "affected_cases": pd.NA,
            "justification": (
                "Both source datasets already passed the predefined quality "
                "threshold; long durations may reflect an open browser session"
            )
        }])
    ],
    ignore_index=True
)

## 16. Validate the cleaned raw dataset

In [27]:
final_audit = pd.Series({
    "rows": len(df),
    "columns": df.shape[1],
    "meta_cases": df["data_source"].eq("meta").sum(),
    "panel_cases": df["data_source"].eq("panel").sum(),
    "unique_response_ids": df["ResponseId"].nunique(),
    "duplicate_response_ids": df["ResponseId"].duplicated().sum(),
    "missing_response_ids": df["ResponseId"].isna().sum(),
    "routine_present": "Routine" in df.columns
})

final_audit

rows                        860
columns                     108
meta_cases                  406
panel_cases                 454
unique_response_ids         860
duplicate_response_ids        0
missing_response_ids          0
routine_present           False
dtype: object

In [28]:
assert len(df) == 860
assert df.shape[1] == 108
assert df["data_source"].eq("meta").sum() == 406
assert df["data_source"].eq("panel").sum() == 454
assert df["ResponseId"].nunique() == 860
assert not df["ResponseId"].duplicated().any()
assert df["ResponseId"].notna().all()
assert "Routine" not in df.columns

print("All final validation checks passed.")

All final validation checks passed.

## 17. Save the cleaned data and cleaning log

The cleaned dataset retains all qualifying respondents. Only documented
technical cleaning operations have been applied.

In [29]:
df.to_excel(
    OUTPUT_PATH,
    index=False
)

cleaning_log.to_excel(
    LOG_PATH,
    index=False
)

print(f"Saved cleaned dataset to: {OUTPUT_PATH.resolve()}")
print(f"Saved cleaning log to: {LOG_PATH.resolve()}")

Saved cleaned dataset to: C:\Users\JonatanPl\OneDrive - JDC\Desktop\Yoni\HighTechProtest - Sampling Wave 2\Python\excel\clean_raw_dataset.xlsx
Saved cleaning log to: C:\Users\JonatanPl\OneDrive - JDC\Desktop\Yoni\HighTechProtest - Sampling Wave 2\Python\excel\cleaning_log.xlsx